/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples
 */
import project.loader.PropertyProjectLoader

plugins {
	id("io.github.gradle-nexus.publish-plugin")
}

allprojects {
	repositories {
		mavenCentral()
		mavenLocal()
		maven {
			setUrl("https://plugins.gradle.org/m2/")
		}
	}
}

nexusPublishing {
	repositories {
		sonatype {
			val env = PropertyProjectLoader.loadAll(rootProject)
			// Configure sonatype account
			stagingProfileId.set(env["OSSRH_PROFILE_ID"] as String?)
			username.set(env["OSSRH_USERNAME"] as String?)
			password.set(env["OSSRH_PASSWORD"] as String?)
		}
	}
}